### ISSUE TITLE
Documentation about BaseView lifecycle

### ISSUE THREAD

**Issue by trietbui85** [SKLn-Rad/provider_assist#1]
Thanks for your lib. Haven't used it yet, but I have a question about its methods. I notice there are 4 methods (`onErrorOccured`, `onEventOccured`, `onModelReady` and `onViewFirstLoad`). What's it in the StatefulWidget lifecycle? Which method should come first?

**Comment by SKLn-Rad** [comment]
Sorry for the slow response! I was on holiday :)
I added a flow diagram to the readme which should clear things up!
