### ISSUE TITLE
Possible merge with provider_architecture from FilledStacks

### ISSUE THREAD

**Issue by elhe26** [SKLn-Rad/provider_assist#3]
Hi,

This is an awesome package. Actually, @FilledStacks has an implementation of his architecture too:
[provider_architecture](https://github.com/FilledStacks/provider_architecture).

Would you think about working with him to unify and develop one architecture?

Regards,

**Comment by FilledStacks** [comment]
@ericklhe I don't think it would be a good fit. I'm aiming to provide tools to build the MvvmArchitecture not a package that builds the architecture for you. This package is basically for me to no re-write the classes I need in ever project. I only use those widgets I have now to build all my apps so adding all the additional stuff that I won't be using is not an option at the moment. 

Thanks for the suggestion though, I'll keep it in mind. If there's anything that I identify that needs to be added then I'll see if it's in here and maybe do a pull request when I get to that point.

**Comment by SKLn-Rad** [comment]
Agreed with above, they serve different purposes :)
My mvvm implementation in this package was 100% based off of FilledStack's implementation (cheers for that!), but its meant to provide a lot more than just that. Its basically a way for me to have everything I need in one place prior to starting an app!
